### ISSUE TITLE
Dont work with the new Preview Hotfix from 9th July

### ISSUE THREAD

**Issue by R0TEAM** [BetterRTX/BetterRTX-Installer#103]
Dont work, GFX Errors - no rendering

**Comment by ABUCKY0** [comment]
Can you elaborate on what you mean?

**Comment by R0TEAM** [comment]
![Screenshot 2024-07-17 172450](https://github.com/user-attachments/assets/02e40033-f916-421f-adbe-c7dee5efda10)

**Comment by R0TEAM** [comment]
In-Game you only see the UI - nothing is rendered

**Comment by R0TEAM** [comment]
And the same with v1.21.20.23 ....

**Comment by ABUCKY0** [comment]
So we are aware this is an issue (I forgot about it when it was mentioned on the 10th). However, I'm going to close this issue since this repository is for the Installer.
