### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by NoaHimesaka1873** [BetterRTX/BetterRTX-Installer#104]
**Describe the bug**
The V1 installer says "Do not distribute" when GPLv3 explicitly allows redistributing.

**To Reproduce**
1. Run installer

**Expected behavior**
No "Do not distribute" text

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Does not matter

**Additional context**
Follow license correctly

**Comment by ABUCKY0** [comment]
lmao i forgot about the gpl license. I'll change that with the next update, whenever that is

**Comment by ABUCKY0** [comment]
At this point, I'm considering the v1 installer functionally deprecated, and therefore I don't plan on updating it anymore.
