### ISSUE TITLE
[HELP] Unable to copy to Minecraft Installation

### ISSUE THREAD

**Issue by iw131** [BetterRTX/BetterRTX-Installer#109]
i chose minecraft for windows

**Comment by ABUCKY0** [comment]
Can you answer the following questions:

1. What installer did you use?
2. What error appeared in the PowerShell window?
3. Did you use a different Bedrock launcher?

**Comment by holytanx** [comment]
Hello, 
I also got this error too. I use Bedrock launcher via Xbox

**Comment by ABUCKY0** [comment]
Since it has been a month since this issue was last updated, I'm assuming you've fixed your issue. If not,  feel free to reply and I can reopen it.
