### ISSUE TITLE
The Minecraft will be not launchable after crash because can not pass the verfication from windows

### ISSUE THREAD

**Issue by linfen0** [BetterRTX/BetterRTX-Installer#18]
# Describe the bug
After I installed the DLSS mod to my minecraft,the error window such like this "can not open the app check the mincrosoft store for help" poped,when i tried to launch the moded minecraft.

Then I consider if it is because the modded nvngx_dlss.dll lead this problem,so I revert the nvngx_dlss.dll manually through Iobitunlock's command(just like the instlaller does,delete modded .dll file,and copy the backuped dll file by iobitunlock),but the error window still poped until i use "repair this app" function in system setting.

After that I refer to the [windows app certificaton test ](https://learn.microsoft.com/en-us/windows/win32/win_cert/windows-app-certification-kit-tests) I noticed this sentence :"All executable files, such as those with file extensions of .exe, .dll, .ocx, .sys, .cpl, .drv, and .scr, must be signed with an Authenticode certificate.".Therefor I consider that error window poped is because the "mod action" itself reasault to The minecraft can not be verificated by windows app,rather than the dll file is wrong. 

# To Reproduce
1. clone the installer prelease version
2. install the exprimental version and DLSS mod to minecraft(v1.19)
3. launch the minecraft and it is still launchable 
4. when crash occured(you know even vaniila minecraft often crash when playing RTX on RTX3050laptop)
relaunch minecraft and that error window poped,then the minecraft become unlaunchable anymore until i use "repair this app" in windows system setting.

# Expected behavior
I wanna know how can i use dlss mod.

# Screenshots
*The error window like belowed*
![2023-05-27_115317](https://github.com/ABUCKY0/BetterRTX-Installer/assets/92668709/01561854-e962-4398-b52c-470b2729e5af)
*The scripts I writted to revert the vanilla DLSS*
![2023-05-27_115459](https://github.com/ABUCKY0/BetterRTX-Installer/assets/92668709/0b8b507d-eef4-4c7f-9ab4-dfc90190b37d)

**Comment by ABUCKY0** [comment]
Yeah this is still an in development feature. I'm not sure as to what caused that, but I will look into it.

**Comment by ABUCKY0** [comment]
I've decided to disable the dlss modding features, since this is a mostly niche feature, and I'm fairly certain it can't be done without a version switcher anyways. for v1.0.1, it probably will be removed entirely.
