### ISSUE TITLE
Error in 1.1.0 installer when trying to uninstall BetterRTX

### ISSUE THREAD

**Issue by ShygalCoco** [BetterRTX/BetterRTX-Installer#29]
**Describe the bug**
An error appears with the 1.1.0 installer when trying to uninstall BetterRTX. I had to switch back to the 1.0.0 installer in order to properly uninstall it.

**To Reproduce**
Just go through the menu to uninstall BetterRTX from Minecraft (not Preview). I don't know if the error happens with Minecraft Preview as I don't use that version of Minecraft.

**Expected behavior**
It would uninstall BetterRTX with no problems.

**Desktop:**
 - OS: Windows 10

**Comment by ABUCKY0** [comment]
Can you add a screenshot of said error?

**Comment by ABUCKY0** [comment]
nvm I've found the error and am resolving it now.
