### ISSUE TITLE
Installer not finding latest versions from server

### ISSUE THREAD

**Issue by ScorNinja** [BetterRTX/BetterRTX-Installer#39]
**Describe the bug**
I assume an error related to "average-visor-eel.cyclic.app" is causing an issue.

**To Reproduce**
1. Fresh install
2. Unable to select version because of error

**Expected behavior**
Expected a list of presets to choose from.

**Screenshots**

```
​_________________________________________________________________________
|    ____           _     _                   _____    _______  __   __   |
|   |  _ \         | |   | |                 |  __ \  |__   __| \ \ / /   |
|   | |_) |   ___  | |_  | |_    ___   _ __  | |__) |    | |     \ V /    |
|   |  _ <   / _ \ | __| | __|  / _ \ | '__| |  _  /     | |      > <     |
|   | |_) | |  __/ | |_  | |_  |  __/ | |    | | \ \     | |     / . \    |
|   |____/   \___|  \__|  \__|  \___| |_|    |_|  \_\    |_|    /_/ \_\   |
|_____________________________QUICK INSTALLER_____________________________|

​_________________________________________________________________________
|                                                                         |
|         This is v1.1.1 of the Quick Installer for Minecraft RTX         |
|            OFFICIAL BetterRTX INSTALLER | DO NOT DISTRIBUTE             |
|_________________________________________________________________________|

Downloading Latest Version List from server
Invoke-WebRequest : The remote name could not be resolved: 'average-visor-eel.cyclic.app'
At C:\Users\scorw\Downloads\BetterRTX_Installer.ps1:243 char:21
+ ...      $releases = Invoke-WebRequest -URI $url -UseBasicParsing | Conve ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Select the Preset to Install!
Select Version:
```

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by ABUCKY0** [comment]
I just checked, the website appears to be working fine for me, however multiple people have had issues with it so I'll be looking into a different host for it.

**Comment by ScorNinja** [comment]
I have figured out the issue. I will follow up in a few minutes.

**Comment by ScorNinja** [comment]
You have to uncheck this box before running installer.

![image](https://github.com/BetterRTX/BetterRTX-Installer/assets/3589484/a6e0216b-173a-4b4e-9bc1-ad9c88a5e7d3)

**Comment by ScorNinja** [comment]
The "Always ask before opening this file" option.

**Comment by ABUCKY0** [comment]
I'm probably still going to switch to a different service anyways, though I don't think that's the issue.

**Comment by ScorNinja** [comment]
Well it failed multiple tries before I unchecked the option and then worked perfectly. Might have something to do with Windows 11 and my firewall settings, but I'm only running the stock Windows Defender settings.
