### ISSUE TITLE
Deleting BetterRTX twice

### ISSUE THREAD

**Issue by MakeSafeTheCity** [BetterRTX/BetterRTX-Installer#44]
For some reason I decided to uninstall BetterRTX twice and now my Minecraft will not work.

**Comment by ABUCKY0** [comment]
1. Did the installer show any errors

If yes, show them here

If not, just try re-uninstalling BetterRTX. Make sure you're on the latest installer version too.

**Comment by ABUCKY0** [comment]
Just checking in, did the issue resolve itself?

**Comment by ABUCKY0** [comment]
Since it's been a week and you haven't responded, I'm closing this issue.
