### ISSUE TITLE
Add ability to select installation folder to support MCLauncher

### ISSUE THREAD

**Issue by Joshua079** [BetterRTX/BetterRTX-Installer#45]
**Is your feature request related to a problem? Please describe.**
 I mean sorta. I'm not installing IOBit just to use this, and if I did it probably still wouldn't work because MCLauncher doesn't use the default installation path. Opening up to MCLauncher would also mean we could use your script without IOBit. 
 
**Describe the solution you'd like**
Allow to input custom Minecraft installation paths which would indirectly open up opportunity to use your script with Version Managers like MCLauncher, along with giving us the option to hopefully not need to install IOBit.

**Comment by ABUCKY0** [comment]
Does MCLauncher allow you to customize the location of where minecraft is installed to outside of a default folder? (I.e. can I put it in my downloads folder if I wanted to). If that's the case, it'd be quite hard to have the install script change it's install location dynamically based on where you have minecraft installed.

**Comment by Joshua079** [comment]
Well sort of. The folder the Minecraft version is installed in will always be the MCLauncher folder, *but* that MCLauncher folder can be anywhere. So maybe we'd need to place the file for your script in the version we want to modify for ease. I'm not sure how you'd go about this if you did take it on but yea the MCLauncher folder can move around but the versions will always stay in that MCLauncher folder.

**Comment by CoolLoong** [comment]
I have the same need, I'm a developer on the community server software and need multiple versions of Minecraft to test, so I use the [MCLauncher](https://github.com/MCMrARM/mc-w10-version-launcher)

**Comment by CoolLoong** [comment]
![image](https://github.com/BetterRTX/BetterRTX-Installer/assets/69153398/8b8a3cd5-982b-46f5-a9f0-cbeac1463e4e)

we can specify the location manually

**Comment by CoolLoong** [comment]
![image](https://github.com/BetterRTX/BetterRTX-Installer/assets/69153398/9fbc0f92-c5b6-4700-bc92-95b6bba45ab1)
Also I found out. MClauncher has modified the install location, if you launch it once
