### ISSUE TITLE
v2 Translations: Afrikaans (af)

### ISSUE THREAD

**Issue by jasonjgardner** [BetterRTX/BetterRTX-Installer#48]
**Add `v2/Localized/af/installer.psd1`**

```powershell
# Afrikaans (af)
ConvertFrom-StringData -StringData @'
    package_name = BetterRTX
    ...
'@
```

### Required Labels
- [ ] backup
- [ ] backup_instance_location
- [ ] browse
- [ ] copying
- [ ] create_initial_backup
- [ ] deleting
- [ ] download
- [ ] downloading
- [ ] error
- [ ] error_copy_failed
- [ ] error_copy_failed_iobit
- [ ] error_copy_failed_pack
- [ ] error_invalid_file_type
- [ ] error_no_installations_selected
- [ ] help
- [ ] install
- [ ] install_custom
- [ ] install_instance
- [ ] install_pack
- [ ] launchers
- [ ] package_name
- [ ] setup
- [ ] success
- [ ] uninstall
- [ ] uninstalled

_See [en-US](https://github.com/BetterRTX/BetterRTX-Installer/blob/main/v2/Localized/en-US/installer.psd1) for source._

**Comment by ABUCKY0** [comment]
some languages require a special name, as listed in [CONTRIBUTING.md](./CONTRIBUTING.md)
