### ISSUE TITLE
better rtx mcpack import error

### ISSUE THREAD

**Issue by nikolayKeniston** [BetterRTX/BetterRTX-Installer#90]
**Describe the bug**
I'm using better render dragon and trying to import mcpack as written in the guide, however minecraft does not allow me to do this. If you copy the pack files directly, Minecraft will complain about "Missing '/subpacks/0/folder_name' element in pack manifest."
![image](https://github.com/BetterRTX/BetterRTX-Installer/assets/139270836/3ed68226-5869-4d11-af4b-b6203ab7b38c)
![image](https://github.com/BetterRTX/BetterRTX-Installer/assets/139270836/fb0cc955-9900-4cea-a44e-b542a97bdc64)
![image](https://github.com/BetterRTX/BetterRTX-Installer/assets/139270836/7ac6237e-199a-45bb-8fb1-bbae44f634ad)

Apparently this shouldn’t have anything to do with my device or OS, it’s just a matter of mcpack

**Comment by nikolay-keenetic** [comment]
I understood what the problem with mcpack - instead of "name" and "folder_name" in the manifest for some reason "description" and "name" were used
![image](https://github.com/BetterRTX/BetterRTX-Installer/assets/139270836/df6f08a7-8b6c-4cd5-8d99-5781edebca29)

**Comment by jasonjgardner** [comment]
Sorry I didn't see this sooner. The .mcpack listed on the README is indeed for Better Render Dragon, not the installer since it has subpacks. I'll look into it.

**Comment by yqs112358** [comment]
> I understood what the problem with mcpack - instead of "name" and "folder_name" in the manifest for some reason "description" and "name" were used ![image](https://private-user-images.githubusercontent.com/139270836/311517468-df6f08a7-8b6c-4cd5-8d99-5781edebca29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTIxMDEsIm5iZiI6MTcxMTExMTgwMSwicGF0aCI6Ii8xMzkyNzA4MzYvMzExNTE3NDY4LWRmNmYwOGE3LThiNmMtNGNkNS04ZDk5LTU3ODFlZGViY2EyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxMjUwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Mjc5YWFiZGRkZTRlMWI2MTFmNGRlMDJmNjdjYzk3ZWE0ZDRlZDA1NGU2MzMyZDc5Yjc0YjBmNTA0ODExNTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LzbRY9qJQFkYmviBCGvxJyLHLZ95PevKVQ11EXFvVzE)

I have renamed all `"description" and "name"` -> `"name" and "folder_name"` in manifest, but the pack still cannot be loaded🥲
Are there any other actions need to be done?

Env: Minecraft Bedrock 1.20.6201 + BetterRenderDragon v1.4.1 Release

**Comment by RowanUnderwood** [comment]
Same issue here - added the folder names and the pack loads now.  But doesn't actually do anything.

**Comment by jasonjgardner** [comment]
> Same issue here - added the folder names and the pack loads now. But doesn't actually do anything.

Can you confirm whether or not you're using [BetterRenderDragon](https://github.com/ddf8196/BetterRenderDragon) and which version of Minecraft?

**Comment by ABUCKY0** [comment]
Since it's been a month without any response, i'm closing this issue. If you're still having issues, feel free to reply and continue the conversation.
